package gui;

import Dto.Carrera;
import Logica.LogicaAplicacion;
import jLabelCronometro.CorredorLlegado;
import jLabelCronometro.CronometroListener;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dbarriof
 */
public class PantallaCronometro extends javax.swing.JDialog {

    private CorredorLlegado corredorLlegado;
    private LogicaAplicacion logicaAplicacion;
    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public PantallaCronometro(java.awt.Frame parent, boolean modal,LogicaAplicacion logicaAplicacion) {
        super(parent, modal);
        this.logicaAplicacion = logicaAplicacion;
        
        initComponents();

        cronometro.addCronometroListener(new CronometroListener() {
            @Override
            public CorredorLlegado llegaCorredor() {
                boolean aniadirLlegada = true;

                CorredorLlegado corredor = new CorredorLlegado();
                corredor.setTiempo(String.valueOf(cronometro.getCronometroDate()));

                while (aniadirLlegada) {
                    String dorsal = JOptionPane.showInputDialog(PantallaCronometro.this, "Indique el dorsal del corredor", "");
                    if (dorsal == null) {
                        JOptionPane.showMessageDialog(PantallaCronometro.this, "La operación se ha cancelado", "Error", JOptionPane.WARNING_MESSAGE);
                        aniadirLlegada = false;
                    } else {
                        if (!dorsal.isEmpty()) {
                            corredor.setDorsal(Integer.parseInt(dorsal));
                            System.out.println(corredor.getDorsal() + " " + corredor.getTiempo());
                            aniadirLlegada = false;
                        } else {
                            int repetirEntrada = JOptionPane.showConfirmDialog(PantallaCronometro.this, "No ha introducido ningún dorsal \n ¿Introducir de nuevo?", "Error", JOptionPane.ERROR_MESSAGE);
                            if (repetirEntrada == JOptionPane.NO_OPTION) {
                                JOptionPane.showMessageDialog(PantallaCronometro.this, "La operación se ha cancelado", "Error", JOptionPane.WARNING_MESSAGE);
                                aniadirLlegada = false;
                            }
                        }
                    }
                }
                return corredor;
            }
        });

    }
    
    public ComboBoxModel<String> cargarCarreras(){
        DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
        for(Carrera carrera:logicaAplicacion.verCarreras()){
            dcm.addElement(carrera.getNombre());
        }
        return dcm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreCarrera = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jButtonLlegadaParticipante = new javax.swing.JButton();
        cronometro = new jLabelCronometro.Cronometro();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombreCarrera.setText("Carrera:");

        jButtonIniciar.setText("Iniciar la carrera");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonParar.setText("Parar carrera");
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });

        jButtonLlegadaParticipante.setText("Llegada de participante");
        jButtonLlegadaParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlegadaParticipanteActionPerformed(evt);
            }
        });

        cronometro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cronometro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cronometroMouseClicked(evt);
            }
        });

        jComboBox1.setModel(cargarCarreras());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLlegadaParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombreCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cronometro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLlegadaParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        cronometro.iniciarCarrera();
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        cronometro.pausarCronometro();
        cronometro.resetCronometro();
    }//GEN-LAST:event_jButtonPararActionPerformed

    private void cronometroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cronometroMouseClicked
        cronometro.aniadirLlegada(evt);
    }//GEN-LAST:event_cronometroMouseClicked

    private void jButtonLlegadaParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlegadaParticipanteActionPerformed
        cronometro.pausarCronometro();
    }//GEN-LAST:event_jButtonLlegadaParticipanteActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jLabelCronometro.Cronometro cronometro;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonLlegadaParticipante;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelNombreCarrera;
    // End of variables declaration//GEN-END:variables
}
